version: '3.8'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - BERT_API_URL=http://bert:8000
    depends_on:
      - bert

  bert:
    build: ./src/bert-service
    ports:
      - '8000:8000'
